### ISSUE TITLE
DLC Motionmapper parallel pool paused?

### ISSUE THREAD

**Issue by annieandbrianneedacode** [AlexEMG/DLCutils#10]
I ran the deeplabcut_into_motionMapper.m using data that I got from DLC and for some reason it stops once it generates figure 7 (see picture below). I have tried running this several times and it always pauses there. It also says "Parallel pool using he 'local' profile is shutting down."

![image](https://user-images.githubusercontent.com/28275585/69266709-908e6200-0bc3-11ea-8cb1-1162cd020769.png)

**Comment by AlexEMG** [comment]
There is an explicit ‘pause' written so that the user can wait to watch the animation. This version is for a demo verision of MotionMapper, you can also check out the original repo: https://github.com/gordonberman/MotionMapper

**Comment by annieandbrianneedacode** [comment]
Ah ok my bad.
