### ISSUE TITLE
time_in_each_roi BUG: counting time when point not in ROI

### ISSUE THREAD

**Issue by FedeClaudi** [AlexEMG/DLCutils#8]
As reported by a user, `time_in_each_roi` consider's the tracked point to be in the closest ROI even if it is, in fact, outside the specified roi box. 
The desired behaviour is that only the time spent when the point is inside the box should be counted. 

I'm reporting this here for reference and will fix it ASAP, will post when fixed.

**Comment by MMathisLab** [comment]
linking here: https://forum.image.sc/t/time-in-each-roi-results-issue/30059 thanks @FedeClaudi

**Comment by FedeClaudi** [comment]
Fixed https://github.com/AlexEMG/DLCutils/pull/9
